# Generated by Django 5.2.1 on 2025-05-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Используйте {{field_1}} для вставки полей')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(help_text='Название для вставки (например: field_1)', max_length=50)),
                ('label', models.CharField(help_text="Подпись поля (например: 'ФИО сотрудника')", max_length=100)),
                ('dictionary', models.ForeignKey(help_text='Откуда брать варианты', on_delete=django.db.models.deletion.CASCADE, to='reports.dictionary')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
        ),
    ]
