# Generated by Django 5.2.1 on 2025-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='content',
            field=models.TextField(help_text='Используйте:\n• {{field_name}} для полей ввода\n• \\t для табуляции\n• \\n для новой строки\n• || для табличных границ', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название шаблона'),
        ),
    ]
