# Generated by Django 5.2.1 on 2025-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reporttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='content',
            field=models.TextField(help_text='Просто пишите текст - переносы строк сохранятся автоматически', verbose_name='Текст шаблона'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
