# Generated by Django 5.2.1 on 2025-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reporttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='content',
            field=models.TextField(help_text='Используйте {{field}} для полей. Пример:\nОтчет подготовил: {{employee}}\nДата: {{date}}'),
        ),
    ]
