# Generated by Django 5.2.1 on 2025-05-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reporttemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('select', 'Выпадающий список'), ('number', 'Числовое поле'), ('text', 'Текстовое поле')], default='select', help_text='Тип поля для ввода', max_length=10),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Максимальное значение (для числовых полей)', null=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Минимальное значение (для числовых полей)', null=True),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='dictionary',
            field=models.ForeignKey(blank=True, help_text='Откуда брать варианты (только для выпадающего списка)', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.dictionary'),
        ),
    ]
