# Generated by Django 5.2.1 on 2025-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dictionary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('select', 'Выпадающий список'), ('number', 'Числовое поле'), ('text', 'Текстовое поле'), ('date', 'Поле даты')], default='select', help_text='Тип поля для ввода', max_length=10),
        ),
    ]
